### ISSUE TITLE
Issue in Creating Coding test

### ISSUE THREAD

**Issue by chiranjeevichiru** [edwisely-ai/Tech-Bridge#267]
Unable to Select Date and Time, they are not aligned properly.

or data and time pop-ups are displayed properly and unable to select them

**Comment by chiranjeevichiru** [comment]
@Prahalya19 please look into this

**Comment by Prahalya19** [comment]
@chiranjeevichiru  - Please provide some screenshots to support the same and also provide browser details - as  I am unable to find this issue in any of my browsers.

**Comment by Prahalya19** [comment]
@chiranjeevichiru  - This is reported to the team. Will be worked on as the first thing for tomorrow.

**Comment by chiranjeevichiru** [comment]
Now even I am getting this issue, refer to the screenshot attached

Browser: chrome

![Screenshot 2021-09-08 090506.jpg](https://images.zenhubusercontent.com/60530434593ffb59252f11d7/c0421202-1d90-4a6e-96c9-c2c455753e01)

**Comment by Prahalya19** [comment]
@chiranjeevichiru - Issue is fixed. You can check now.
