### ISSUE TITLE
Submitted the test but Shows "Start Test" Again

### ISSUE THREAD

**Issue by kautilyabo** [edwisely-ai/Tech-Bridge#269]
ID : 21107
Name: KUMARA VIJAY M G
Reg.no:111720104078
Mail ID: kuma20231.ec@rmkec.ac.in
Issue: SUBMITTED THE TEST BUT SHOWS START TEST AGAIN .

Called the student. Has stable internet connection. He took the test and submitted it on the web portal.  After submitting immediately was showing as "Start Test". He had only 2 minutes gap till the test expired so he did not try tapping on it. 

After the test expired he did not get the Results, was showing as test expired.

He mentioned happening to one of his friends the previous day.

![image.png](https://images.zenhubusercontent.com/605308344472d103f746bd46/92f3cea5-da70-403e-9d65-389f48e0d6a4)

**Comment by Prahalya19** [comment]
@kautilyabo - Can't find much insights on this. We will once check this through.

**Comment by Prahalya19** [comment]
@kautilyabo - Can't find much insights on this. We will once check this through.

**Comment by Prahalya19** [comment]
@kautilyabo - Please check if this scenario is happening again. Else close this as the recent fix should also handle this case.
