### ISSUE TITLE
Shows test submitted without completing

### ISSUE THREAD

**Issue by kautilyabo** [edwisely-ai/Tech-Bridge#270]
The issue in taking the unit test in RMK next gen 
ID :  21182
Name: T.Sriram
Reg no: 111720104154
Phone :  9080380729
Mail id: srir20417.ec@rmkec.ac.in
Issue: shows test submitted without completing

A student was trying to take a test on the RMK Nextgen Web Portal 
To his first test yesterday and it went well. Today when clicked on "Start Test", it refreshed and showed him "Test Submitted".  
Nothing happened in between. Not even instructions are shown. 
Cannot see a test submission event in amplitude too. 

Approx Time of taking the exam : 2.35 pm, 07, Sept .

![WhatsApp Image 2021-09-07 at 14.43.59.jpeg](https://images.zenhubusercontent.com/605308344472d103f746bd46/f97d7581-5ea2-4562-8090-f0e9ef551924)

**Comment by Prahalya19** [comment]
@kautilyabo - As discussed, the DB shows that student has spent 31 seconds in the test.
Also, from what is mentioned by the student he hasn't seen the instructions page as well . If this is the case, there is No way the test can get submitted. Please confirm on the entire flow with the student once.

**Comment by kautilyabo** [comment]
He took the test on the Web Portal. Clicking on the first "start test" button without going into the instructions page , a reload sign came up and the page reloaded and submitted.

**Comment by Prahalya19** [comment]
@kautilyabo - Please check if this is happening, else close this.

**Comment by kautilyabo** [comment]
This is being merged with the "Test Submitted on clicking Start Test" ticket as it is the same web portal issue. Closing it here

**Comment by Prahalya19** [comment]
@kautilyabo - Please verify and close this issue
