### ISSUE TITLE
Able to view results on webportal but not on the Edwisely iOS App.

### ISSUE THREAD

**Issue by kautilyabo** [edwisely-ai/Tech-Bridge#271]
Name : Shri Abijith.M
ID:  	21173
Reg.no: RMKUEC20408
Mail. I’d : shri20408.ec@rmkec.ac.in
Phone : 6385160799
Issue: completed the maths test on 6.9.21 but the result is not shown .

Had a call with the student. He wrote the test in the Web portal. He was trying to access the results from the Edwisely iOS App, which was showing as test expired . 
On the web portal, he's able to view the results but not on the Edwisely App.

![WhatsApp Image 2021-09-07 at 16.05.57.jpeg](https://images.zenhubusercontent.com/605308344472d103f746bd46/8b834711-5b8a-4274-95ba-e6dc3714735f)

**Comment by Prahalya19** [comment]
@kautilyabo - As discussed, please check with the candidate once again. 

Kindly try app uninstall and install - since it is working as expected in our Android and iOS devices.

**Comment by kautilyabo** [comment]
He's able to view the results in iOS App now. The issue has been resolved.
