### ISSUE TITLE
Test submitted but showing expired.

### ISSUE THREAD

**Issue by kautilyabo** [edwisely-ai/Tech-Bridge#273]
ID: 18201
R NO : 111619104135
Name : SHAKTI A S
Phone :  	8248487673

Issue Reported: Sir yesterday I took the test around 4.. I didn't navigate or nothing disturbed the test.. I took it in my laptop.. The test was also submitted successfully.. But now results are not shown. It says test has expired. But my friends got their result..

Info : 
The student wrote the test on web portal and it showed successfully submitted. After submitting in the web portal she was able to see that the test was submitted too. No Start test was showing up. Today morning she checked for results and it wasn't showing up. 

![WhatsApp Image 2021-09-08 at 11.54.29.jpeg](https://images.zenhubusercontent.com/605308344472d103f746bd46/011ff091-5db1-4af5-9a25-084baf068ad6)

**Test ID** : 6258 
**No submission found** : SELECT * FROM `questionnaire_submission` WHERE questionnaire_id = 6258 && student_id = 18201

**Comment by Prahalya19** [comment]
@kautilyabo - Please confirm if these issues are still happening. The fix was these was rolled out around 5 days ago.
