### ISSUE TITLE
Test Submitted on clicking Start Test

### ISSUE THREAD

**Issue by kautilyabo** [edwisely-ai/Tech-Bridge#275]
ID : 21191
Roll Number : RMKUEC20427 	
Name : THALAPANENI TEJASWINI
Phone : 9154802753

Issue : 
Took a test on the web portal. clicked on start test. on the instructions page upon clicking start test , shown as test submitted.

Test Details : 
Second Test in the Image

![WhatsApp Image 2021-09-08 at 16.21.44.jpeg](https://images.zenhubusercontent.com/605308344472d103f746bd46/23985fed-7664-48aa-843e-aa8f20d60042)

![image.png](https://images.zenhubusercontent.com/605308344472d103f746bd46/6bb9092d-d4a8-407a-814d-9c1294dfb31a)

Test Submitted : 
![image.png](https://images.zenhubusercontent.com/605308344472d103f746bd46/3accd32b-e35f-4147-90ca-8616bd451a90)

**Comment by kautilyabo** [comment]
Student 2 : Issue with same test 
ID : 21036
RMKUEC20104
ABDUL HAKEEM S H

**Comment by kautilyabo** [comment]
Student 2 : Issue with the same test, exact same scenario
ID:  	21134
RMKUEC203
MULE LEELA KRISHNA REDDY
7660903856

![image.png](https://images.zenhubusercontent.com/605308344472d103f746bd46/be9a366c-52fb-406a-97e1-f6f60819b292)

**Comment by kautilyabo** [comment]
Student 4 : Issue with the two test, exact same scenario
Id : 21038
RMKUEC20106
ABINAYA R
9345697695

Submision ID : 
![image.png](https://images.zenhubusercontent.com/605308344472d103f746bd46/beeeaf3f-a9b1-493e-922a-768468b99ce6)

**Comment by kautilyabo** [comment]
Student 5 : 

21074
RMKUEC20142
DURGESAM SURYA
9848224513

@Prahalya19 
The issue with a test on the web portal, has logged in, clicked on start test in the dashboard, automatically shown as test submitted. no instructions page is shown.
No other tabs open, no add ons to the browser.

Test Details : 
![WhatsApp Image 2021-09-09 at 15.54.46.jpeg](https://images.zenhubusercontent.com/605308344472d103f746bd46/cc73f16f-2768-48e0-8453-318a69491871)

Submission ID :
![image.png](https://images.zenhubusercontent.com/605308344472d103f746bd46/8cf8aea7-4e58-43b3-abb7-3228ea4facdb)

**Comment by kautilyabo** [comment]
Student 6; 
ID : 21182
Name: T.Sriram
Reg no: 111720104154
Phone : 9080380729
Mail id: srir20417.ec@rmkec.ac.in

Issue : 
A student was trying to take a test on the RMK Nextgen Web Portal
Took his first test on 6th Sept and it went well. On 7th Sept, when clicked on "Start Test", it refreshed and showed him "Test Submitted".
Nothing happened in between. Not even instructions are shown.

**Comment by Prahalya19** [comment]
@kautilyabo - As mentioned to you on 8th Sept - this issue was handled. Please check if they are having any issues post that.
