### ISSUE TITLE
Everytime I try to view your result/start/take test button, it automatically exits the app.

### ISSUE THREAD

**Issue by kautilyabo** [edwisely-ai/Tech-Bridge#276]
Id : 18872
111719106040
GEETHIKA K N
9884362463

Issue : 
I can't seem to take the test set up for us in the R.M.K. NextGen app.
The app still quits automatically every time I click on the view your result/start/take test button.

Device Details : 
Mi 11X

![WhatsApp Image 2021-09-14 at 13.24.01.jpeg](https://images.zenhubusercontent.com/605308344472d103f746bd46/84afd2d3-44be-4ee5-886f-54e33c8d1fdb)
![WhatsApp Image 2021-09-14 at 13.32.58.jpeg](https://images.zenhubusercontent.com/605308344472d103f746bd46/010a7df0-cf9a-4e2d-819b-4349aee50c4b)

![4a85443a-846a-4eaa-b76e-5e77fff7b4a5.png](https://images.zenhubusercontent.com/605308344472d103f746bd46/b40e1b36-295a-48de-972d-fa58ae0308c5)

https://images.zenhubusercontent.com/348995076/d2b93886-5bfb-41e5-8581-ac2f7f3c3c83/whatsapp_video_2021_09_07_at_22_40_26.mp4

https://images.zenhubusercontent.com/348995076/b4de4146-0997-494f-845f-a422e4eb249c/whatsapp_video_2021_09_07_at_22_40_46.mp4

https://images.zenhubusercontent.com/348995076/d829b0c4-a87d-4369-b6a9-ff9512fa822e/whatsapp_video_2021_09_09_at_19_53_52.mp4

Here, as you can see, clicking on the "view your result" option but it automatically quits the app just like every other time : 
https://images.zenhubusercontent.com/350592437/2a3950f3-955d-406e-a639-882887b55251/whatsapp_video_2021_09_10_at_17_30_35.mp4

**Comment by Prahalya19** [comment]
@kautilyabo - Can you please provide the device details as well.

**Comment by Prahalya19** [comment]
@kautilyabo - Will check with the developer and let you know.

**Comment by Prahalya19** [comment]
@kautilyabo - Was this issue happening for the student in the Edwisely app previously? If not sure, can you ask them to take 1 test from there and update the status.

**Comment by kautilyabo** [comment]
@Prahalya19 
She took tests in the Edwisely app before and only had issues in the early stages. Not after that. 
Now provided the apk again. will update you on the results.

**Comment by kautilyabo** [comment]
@Prahalya19 
The student is able to take a test with the Edwisely 2.5.0 version of the App.

**Comment by Prahalya19** [comment]
@kautilyabo - As per our conversation, is the student able to take the tests after switching off the dark mode in the RMK Nextgen app?

**Comment by kautilyabo** [comment]
@Prahalya19  -The student was able to take a test in the edwisely app, in a particular test she was but was not able to see options (was able to see questions) in the app, switching off the dark mode has rectified that issue. 

In the RMK Next Gen app irrespective of a dark mode on or off, the tests were crashing.

**Comment by kautilyabo** [comment]
@Prahalya19  Clearing data again has rectified the issue for the user. Venkat has crash analytics recorded through firebase for debugging purposes.
