### ISSUE TITLE
Coding Exam Issue on 15092021

### ISSUE THREAD

**Issue by chiranjeevichiru** [edwisely-ai/Tech-Bridge#284]
issue-1: 

use web app error while in 2nd question, even though using laptop)
![issue 3.jpg](https://images.zenhubusercontent.com/60530434593ffb59252f11d7/ab787bbd-8c29-47eb-a995-d2d31e24a245)

**Comment by chiranjeevichiru** [comment]
Test detail:
![WhatsApp Image 2021-09-15 at 3.43.25 PM.jpeg](https://images.zenhubusercontent.com/60530434593ffb59252f11d7/68178d76-fa20-4492-b0e7-647cd1b0e59d)

**Comment by chiranjeevichiru** [comment]
try RMKACS3

**Comment by Prahalya19** [comment]
@chiranjeevichiru - Did we get any insights on how the faculty created the test without marks and widget code?

**Comment by chiranjeevichiru** [comment]
No @Prahalya19, I think it's not a good idea to get back to the faculty, if you have an idea on why the issue has occurred then reproducing it and resolving would be more appropriate, what Say?

**Comment by Prahalya19** [comment]
@chiranjeevichiru - My question was not on checking with the faculty. On that day, we have discussed that you will test it and see how was that possible. My question was do we have any insights based on that?

**Comment by chiranjeevichiru** [comment]
@Prahalya19 No, Need to test it.

**Comment by Prahalya19** [comment]
Issue resolved
