### ISSUE TITLE
IOS RMK Nextgen Student App - Testflight - Crash on 18092021

### ISSUE THREAD

**Issue by chiranjeevichiru** [edwisely-ai/Tech-Bridge#289]
Testflight - IOS RMK Nextgen Student App verion 1.0(1.5).

App crashed after answering QOD and It is still crashing whenever I open the app.

**Comment by Prahalya19** [comment]
@vickyse91 - Please check and update on this.

**Comment by vigneshtfe** [comment]
@Prahalya19 @chinmaymisra  Issue cleared .. Please check with the latest build RMK Nextgen Student 1.0 (1.5)

**Comment by Prahalya19** [comment]
@chiranjeevichiru - Kindly check and close
