### ISSUE TITLE
[NextGen Android] Showing "Try again after some time !" when trying to take a test 

### ISSUE THREAD

**Issue by kautilyabo** [edwisely-ai/Tech-Bridge#290]
ID: 17792
Roll Number : 111519106009
BALAVIGNESH A
8681860577

Issue : Showing "Try again after some time !" when trying to take a test. Clearing cache and full troubleshooting didn't work.

@Prahalya19 Please have a look at the video too.
https://images.zenhubusercontent.com/350592437/2c941ec8-4d05-4909-8f66-b0f142c4e8a1/whatsapp_video_2021_09_18_at_13_28_27.mp4

Device details :
realme RMX3360
![image.png](https://images.zenhubusercontent.com/605308344472d103f746bd46/fe5f36b0-4276-452e-863c-e1ecb7f215dc)
![WhatsApp Image 2021-09-18 at 13.28.27.jpeg](https://images.zenhubusercontent.com/605308344472d103f746bd46/b6f75da7-a750-4c99-87eb-860f151a2eaa)

**Comment by Prahalya19** [comment]
Vengat, please check this.

**Comment by avengat** [comment]
Can you pls ask them to enable the phone permission, then try one more time!

**Comment by Prahalya19** [comment]
@kautilyabo - Can you please follow up on the point mentioned by Vengat.

**Comment by kautilyabo** [comment]
He was not asked for phone permissions when trying to take a test. So he manually added them by going into the app info. Yet he is having the same issue while trying to take a test.

**Comment by avengat** [comment]
ok. I will check and update you!

**Comment by avengat** [comment]
@kautilyabo 
Is this issue still persists in new version?

**Comment by kautilyabo** [comment]
I will check and let you know tomorrow.

**Comment by avengat** [comment]
ISSUE FIXED!
TEST APK : https://drive.google.com/file/d/1Fywh_FQErVT5dRhYP26KXqz5GMclMAX_/view?usp=sharing

**Comment by kautilyabo** [comment]
@RAJASEKHAR36 Can you test the above apk?
- It fixes start test issue.

@Prahalya19 Please let raj know if needs to test anything more in this staging apk.
