### ISSUE TITLE
Coding Assessment 15092021 - Widget Code 

### ISSUE THREAD

**Issue by chiranjeevichiru** [edwisely-ai/Tech-Bridge#291]
Widget code wasn't updated automatically

Please find the test details and error that occurred in Sphere Engine.

![c2-3.jpeg](https://images.zenhubusercontent.com/60530434593ffb59252f11d7/448291ef-1d85-4866-91fa-e9e4e979c505)

![c2-2.jpeg](https://images.zenhubusercontent.com/60530434593ffb59252f11d7/e13a3409-6357-4ee6-abe6-749dfcacd80c)

![c2 -1.jpeg](https://images.zenhubusercontent.com/60530434593ffb59252f11d7/43afae51-da43-479a-b4eb-4ee3b086e59a)

**Comment by Prahalya19** [comment]
@chiranjeevichiru - Issue resolved
