### ISSUE TITLE
[Android App] Classroom Tab Crashing

### ISSUE THREAD

**Issue by kautilyabo** [edwisely-ai/Tech-Bridge#294]
Issue : 
The classroom Tab is crashing. So not able to see the results.

She is onboarded nearly 3 weeks back and has recognized this issue recently when she took the tests and was trying to view results.
She has performed the troubleshooting yet the issue persists. 

@Prahalya19 Please look into this and let me know if you need anything.

Student Details : 
ID : 22910
Name: YUTHIKA G
Email: YUTH21438.CS@rmkec.ac.in
Phone Number : 7305376137
Roll Number : UCS21438

Device Details :
Lenovo Tab M8

![image.png](https://images.zenhubusercontent.com/605308344472d103f746bd46/8449c2bb-829c-4d11-ba01-f3c883fdc7db)

https://images.zenhubusercontent.com/350592437/187ce286-e539-41b0-98cf-5d0b5472a400/whatsapp_video_2021_11_25_at_6_39_42_pm.mp4

**Comment by Prahalya19** [comment]
@avengat - Please check

**Comment by avengat** [comment]
@Prahalya19 
Got the reason for this issue. 
Its due to the layout missmatching, while open the app in high resoltution devices it is occuring!
We have to upload new version in playstore with this issue fix!
Before that we have to check the old version & new version in any tablet then we have to release! (I have tested in emulator, both old version and new version. Old version got crash and new version that issue fixed and working fine)

**Comment by Prahalya19** [comment]
@kautilyabo, @RAJASEKHAR36  - Can you please support @avengat in checking this out on the real devices as well. 

Once confirmed this can be rolled out in the immediate next release.

**Comment by kautilyabo** [comment]
Okay Prahalya. I don't have an android device with me anymore so I can try using an emulator only. 
If @avengat provides the build, @RAJASEKHAR36 could test it out.

**Comment by avengat** [comment]
@kautilyabo Will release new student staging app once QOD issue also fixed!

**Comment by avengat** [comment]
ISSUE FIXED!
TEST APK : https://drive.google.com/file/d/1Fywh_FQErVT5dRhYP26KXqz5GMclMAX_/view?usp=sharing

**Comment by kautilyabo** [comment]
@Prahalya19 This will be released in the next Playstore build and that's when the issues will be fixed for the actual students right?

**Comment by Prahalya19** [comment]
@kautilyabo - Yes, we will be releasing the builds this weekend. They are already tested and approved. However, device specific issues were only checked by @avengat on his emulator. @RAJASEKHAR36 is unable to test them through his device.
