### ISSUE TITLE
Question of the Day - One time Bug

### ISSUE THREAD

**Issue by kautilyabo** [edwisely-ai/Tech-Bridge#295]
Hey Prahalya. 

A student faced an issue with QOD yesterday, where he has selected the correct option and got the message "Correct Answer". He was somehow seeing the 4th option of the question below the graph and taped on it by mistake. the QOD card changed to "wrong answer" and later when he restarts the app, he saw that his original answer is registered i.e "Correct Answer" is showing in the QOD card. 

Please see if we can do anything about this bug.

Student Details : 
ID : 22486
J PRAKASH
9283184649

Device Details : 
Vivo V2058 / Vivo Y53s
![image.png](https://images.zenhubusercontent.com/605308344472d103f746bd46/06fc9e6c-a25a-4df0-89c2-ef56e102c45b)

**Comment by Prahalya19** [comment]
@avengat - Please check this out.

Also, is a student able to answer the same question again. Kindly check this.

@RAJASEKHAR36 - Can you please check all the student applications and see from where all are the students able to answer and already attempted Question of the day?

**Comment by avengat** [comment]
@Prahalya19 @kautilyabo ok im checking
