### ISSUE TITLE
[NextGen Android] Not able to take a test or view results

### ISSUE THREAD

**Issue by kautilyabo** [edwisely-ai/Tech-Bridge#296]
Issue : 
The student is not able to take a test or view results via the mobile app. It is stuck on a loading page he clicked on the button in the test card.
https://images.zenhubusercontent.com/350592437/969d0ac1-bfe5-4612-8f5c-82abe4bc3c52/whatsapp_video_2021_11_29_at_1_34_07_pm.mp4

Student Details : 
23317
UME21117
KISHORE T
7904294885

Device Details : 
Oppo A57
Android 6.0.1
![image.png](https://images.zenhubusercontent.com/605308344472d103f746bd46/edba1529-c4c7-43ec-9396-cf2c0d9c56e1)

He is following the troubleshooting options, I'll update you once he goes through it.

**Comment by kautilyabo** [comment]
This issue has been resolved when the student followed the [troubleshooting ](https://blog.edwisely.com/help/educator/troubleshooting-tips-for-edwisely-platform/) tips.

Can we have a look into why this was happening in the first place? Or else we can close the issue.

**Comment by Prahalya19** [comment]
@kautilyabo - Can you please confirm the version of the app the student was using? Is this the very first time he is opening a test after our release? 
Mostly this is an issue with the old cache of the test url.

**Comment by kautilyabo** [comment]
He was using app v1.3 as you can see in the screenshot. Verified from the student too. 

I'll get back to you on "opening the test first time after release or not."

**Comment by Prahalya19** [comment]
@kautilyabo - Please let me know if there is any update on this.

**Comment by kautilyabo** [comment]
The issue has been resolved @Prahalya19  . The student is able to access the test info from mobile.
