### ISSUE TITLE
SAIL App Student - Issues - 04/02/2022 to 05/02/2022

### ISSUE THREAD

**Issue by chiranjeevichiru** [edwisely-ai/Tech-Bridge#310]
Students issues while taking tests.

https://images.zenhubusercontent.com/348994383/de3386f7-854b-46e6-97d1-52d3e0d24ecc/whatsapp_video_2022_02_05_at_7_19_24_pm.mp4

https://images.zenhubusercontent.com/348994383/d916e6b5-3c98-4089-98e0-8e6d559af8da/whatsapp_video_2022_02_05_at_6_35_00_pm.mp4

![WhatsApp Image 2022-02-05 at 7.43.03 PM.jpeg](https://images.zenhubusercontent.com/60530434593ffb59252f11d7/071d3759-1804-4096-90ba-abb186fe5926)

![WhatsApp Image 2022-02-05 at 7.16.19 PM.jpeg](https://images.zenhubusercontent.com/60530434593ffb59252f11d7/adccb15d-bf10-4760-ac93-eaaef5cf4b5d)

![WhatsApp Image 2022-02-05 at 7.57.28 PM.jpeg](https://images.zenhubusercontent.com/60530434593ffb59252f11d7/5ae0adcd-46ad-476b-b4e5-475a52288104)

![WhatsApp Image 2022-02-05 at 8.09.54 PM.jpeg](https://images.zenhubusercontent.com/60530434593ffb59252f11d7/fb7239f7-7962-42ac-9968-76ab3eb32585)

![WhatsApp Image 2022-02-05 at 8.39.03 PM.jpeg](https://images.zenhubusercontent.com/60530434593ffb59252f11d7/373e8028-1b52-4bfd-bfce-ff51235f0103)

![WhatsApp Image 2022-02-05 at 7.09.13 PM.jpeg](https://images.zenhubusercontent.com/60530434593ffb59252f11d7/1bc97765-1360-4dfe-bc76-1cd078b3a510)

![WhatsApp Image 2022-02-05 at 7.31.19 PM.jpeg](https://images.zenhubusercontent.com/60530434593ffb59252f11d7/429add27-5bf4-489f-9744-7611ac62e04c)

![WhatsApp Image 2022-02-05 at 7.31.25 PM.jpeg](https://images.zenhubusercontent.com/60530434593ffb59252f11d7/7a0e9d15-e9ad-4794-9cd9-0e59de74b351)

**Comment by chiranjeevichiru** [comment]
@Prahalya19 @RAJASEKHAR36 @avengat creating an issue for the record, and I am aware that the Team is already working on it, Kudos Team for all the Endless efforts, Hope we have a Solution now and kindly share the Update once you are done. Thank you

**Comment by Prahalya19** [comment]
@chiranjeevichiru - The issue is resolved
